[package]
name = "gst-plugin"
version = "0.1.0"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]
build = "build.rs"
repository = "https://github.com/sdroege/rsplugin/gst-plugin"
license = "LGPL-2.1+"

[dependencies]
libc = "0.2"
url = "1.1"
bitflags = "0.7"
slog = { version = "1.3", features = ["max_level_trace"] }
lazy_static = "0.2"
byteorder = "1.0"

[build-dependencies]
gcc = "0.3"
pkg-config = "0.3"

[lib]
name = "gst_plugin"
path = "src/lib.rs"
