[workspace]

members = [
    "gst-plugin-file",
    "gst-plugin-http",
    "gst-plugin-flv",
    "gst-plugin-audiofx",
    "gst-plugin-togglerecord",
    "gst-plugin-threadshare",
    "gst-plugin-tutorial",
    "gst-plugin-closedcaption",
    "gst-plugin-sodium",
]

[profile.release]
lto = true
opt-level = 3
debug = true
panic = 'unwind'
