[package]
name = "rsplugin"
version = "0.1.0"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]
build = "build.rs"

[dependencies]
libc = "0.2"
url = "1.1"
hyper = "0.9"

[build-dependencies]
gcc = "0.3"
pkg-config = "0.3"

[lib]
name = "rsplugin"
crate-type = ["dylib"]
path = "src/lib.rs"
