[workspace]

members = [
    "gst-plugin",
    "gst-plugin-file",
    "gst-plugin-http",
    "gst-plugin-flv",
    "gst-plugin-audiofx",
]

[profile.release]
lto = true
debug-assertions = false
opt-level = 3
debug = true
panic = 'unwind'
