[advisories]
db-path = "~/.cargo/advisory-db"
db-url = "https://github.com/rustsec/advisory-db"
vulnerability = "deny"
unmaintained = "warn"
notice = "warn"
ignore = [
    # ignore because mio/miow still depend on net2, next mio release fixes this
    "RUSTSEC-2020-0016"
]

[licenses]
unlicensed = "deny"
allow = [
  "Apache-2.0",
]
deny = [
  "GPL-1.0",
  "GPL-2.0",
  "GPL-3.0",
  "AGPL-1.0",
  "AGPL-3.0",
]
copyleft = "allow"
allow-osi-fsf-free = "either"
confidence-threshold = 0.8

[bans]
multiple-versions = "deny"
highlight = "all"

# ignore duplicated deps because of hyperx and rust-argon2 via redox_users
# depending on old base64
# https://github.com/dekellum/hyperx/pull/20
# https://gitlab.redox-os.org/redox-os/users/-/merge_requests/34
[[bans.skip]]
name = "base64"
version = "0.11"

# ignore duplicated deps because of dav1d-sys via metadeps depending on old
# error-chain and toml
# https://github.com/rust-av/dav1d-rs/issues/26
# https://github.com/joshtriplett/metadeps/pull/12
# https://github.com/joshtriplett/metadeps/pull/4
[[bans.skip]]
name = "error-chain"
version = "0.10"
[[bans.skip]]
name = "toml"
version = "0.2"

# ignore duplicated deps because of url via cookie-store via request depending
# on old url, idna and percent-encoding
# https://github.com/pfernie/cookie_store/issues/11
[[bans.skip]]
name = "url"
version = "1.0"
[[bans.skip]]
name = "idna"
version = "0.1"
[[bans.skip]]
name = "percent-encoding"
version = "1.0"

# ignore duplicated deps because of mio-named-pipes via mio depending on old
# miow
# https://github.com/alexcrichton/mio-named-pipes/issues/7
[[bans.skip]]
name = "miow"
version = "0.2"
[[bans.skip]]
name = "winapi"
version = "0.2"

# ignore duplicated deps because of chrono, cookie, cookie_store, hyper,
# hyperx, reqwest depending on old time
# https://github.com/chronotope/chrono/issues/400
# https://github.com/pfernie/cookie_store/issues/11
# https://github.com/hyperium/hyper/pull/2139
# https://github.com/dekellum/hyperx/issues/21
# https://github.com/seanmonstar/reqwest/issues/934
[[bans.skip]]
name = "time"
version = "0.1"

# ignore duplicated tokio dep because of gst-plugin-threadshare having its own
# fork
# https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/-/issues/118
[[bans.skip]]
name = "tokio"
version = "0.2.13"
[[bans.skip]]
name = "tokio-macros"

# ignore duplicated textwrap dependency because clap depends on an old version
# https://github.com/clap-rs/clap/pull/1994
[[bans.skip]]
name = "textwrap"
version = "0.11"

# ignore duplicated miniz_oxide dependency because png/tiff depend on an old version
# https://github.com/image-rs/image-tiff/pull/76
# https://github.com/image-rs/image-png/pull/235
[[bans.skip]]
name = "miniz_oxide"
version = "0.3"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = [
  "https://gitlab.freedesktop.org/gstreamer/gstreamer-rs",
  "https://gitlab.freedesktop.org/gstreamer/gstreamer-rs-sys",
  "https://github.com/gtk-rs/sys",
  "https://github.com/gtk-rs/glib",
  "https://github.com/gtk-rs/gio",
  "https://github.com/gtk-rs/cairo",
  "https://github.com/gtk-rs/pango",
  "https://github.com/gtk-rs/pangocairo",
  "https://github.com/gtk-rs/atk",
  "https://github.com/gtk-rs/gdk-pixbuf",
  "https://github.com/gtk-rs/gdk",
  "https://github.com/gtk-rs/gtk",
  "https://github.com/fengalin/tokio",
  "https://github.com/rust-av/flavors",
]
