[package]
name = "gst-plugin-flv"
version = "0.1.0"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]
repository = "https://github.com/sdroege/rsplugin"
license = "MIT/Apache-2.0"

[dependencies]
url = "1.1"
gst-plugin = { path="../gst-plugin" }
slog = "2.0"
nom = "3.0"
flavors = {git = "https://github.com/rust-av/flavors.git"}

[lib]
name = "gstrsflv"
crate-type = ["cdylib"]
path = "src/lib.rs"
