[package]
name = "gst-plugin-file"
version = "0.1.0"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]
repository = "https://github.com/sdroege/rsplugin"
license = "LGPL-2.1+"

[dependencies]
url = "1.1"
gst-plugin = { path="../gst-plugin" }
slog = "1.3"

[lib]
name = "gstrsfile"
crate-type = ["cdylib"]
path = "src/lib.rs"
